package socialenterprise.eligrules;

rule "ColoradoRegionRules"
	ruleflow-group "Colorado"
	dialect "mvel"
	when
		member : MemberDO( subage > 0 , subage <= 35 , FPL <= 300,spouseage>0,spouseage<=26 )
	then
		member.setRegionrule( "Yes" );
end

rule "GeorgiaRegionRulesBigfamily"
	ruleflow-group "Georgia"
	dialect "mvel"
	when
		member : MemberDO( subage > 0 , subage <= 65 , FPL <= 300,familysize>1 )
	then
		member.setRegionrule( "Yes" );
end

rule "GeorgiaRegionRules1"
	ruleflow-group "Georgia"
	dialect "mvel"
	when
		member : MemberDO( subage > 18 , subage <= 65 , FPL <= 300,familysize<=1 )
	then
		member.setRegionrule( "Yes" );
end