package socialenterprise.eligrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class eligrulestatusDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Member ID")
   private java.lang.Integer memberid;
   @org.kie.api.definition.type.Label(value = "Rule and result")
   private java.util.List<java.lang.String> ruleandresult;

   public eligrulestatusDO()
   {
   }

   public java.lang.Integer getMemberid()
   {
      return this.memberid;
   }

   public void setMemberid(java.lang.Integer memberid)
   {
      this.memberid = memberid;
   }

   public java.util.List<java.lang.String> getRuleandresult()
   {
      return this.ruleandresult;
   }

   public void setRuleandresult(java.util.List<java.lang.String> ruleandresult)
   {
      this.ruleandresult = ruleandresult;
   }

   public eligrulestatusDO(java.lang.Integer memberid,
         java.util.List<java.lang.String> ruleandresult)
   {
      this.memberid = memberid;
      this.ruleandresult = ruleandresult;
   }

}