package socialenterprise.eligrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class eligrulestatusDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Member ID")
   private java.lang.Integer memberid;
   @org.kie.api.definition.type.Label(value = "ServiceAreaRule")
   private java.lang.Boolean servicearearule;

   @org.kie.api.definition.type.Label(value = "Region Rule")
   private boolean regionrule;

   public eligrulestatusDO()
   {
   }

   public java.lang.Integer getMemberid()
   {
      return this.memberid;
   }

   public void setMemberid(java.lang.Integer memberid)
   {
      this.memberid = memberid;
   }

   public java.lang.Boolean getServicearearule()
   {
      return this.servicearearule;
   }

   public void setServicearearule(java.lang.Boolean servicearearule)
   {
      this.servicearearule = servicearearule;
   }

   public boolean isRegionrule()
   {
      return this.regionrule;
   }

   public void setRegionrule(boolean regionrule)
   {
      this.regionrule = regionrule;
   }

   public eligrulestatusDO(java.lang.Integer memberid,
         java.lang.Boolean servicearearule, boolean regionrule)
   {
      this.memberid = memberid;
      this.servicearearule = servicearearule;
      this.regionrule = regionrule;
   }

}