package socialenterprise.eligrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MemberDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Subscriber Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Zip Plus Four")
   private java.lang.String zip;
   @org.kie.api.definition.type.Label(value = "Member or Subscriber ID")
   private java.lang.Integer memberid;
   @org.kie.api.definition.type.Label(value = "Total Family Income")
   private java.lang.Integer totalfamilyincome;
   @org.kie.api.definition.type.Label(value = "Personal Income Factor")
   private java.lang.Integer personalincomefactor;
   @org.kie.api.definition.type.Label(value = "Family Size")
   private java.lang.Integer familysize;
   @org.kie.api.definition.type.Label(value = "Additional Income Factor")
   private java.lang.Integer additionalyfactor;
   @org.kie.api.definition.type.Label(value = "Region")
   private java.lang.String region;
   @org.kie.api.definition.type.Label(value = "FPL")
   private java.lang.Integer FPL;
   @org.kie.api.definition.type.Label(value = "Subcriber age")
   private java.lang.Integer subage;
   @org.kie.api.definition.type.Label(value = "Age of Spouse")
   private java.lang.Integer spouseage;
   @org.kie.api.definition.type.Label(value = "Dependent 1 Age")
   private java.lang.Integer dep1age;
   @org.kie.api.definition.type.Label(value = "Dependent 2 Age")
   private java.lang.Integer dep2age;
   @org.kie.api.definition.type.Label(value = "Overall Eligiblity Rule1")
   private java.lang.String overalleligrule1;
   @org.kie.api.definition.type.Label(value = "Overall Eligibility Rule2")
   private java.lang.String overalleligrule2;
   @org.kie.api.definition.type.Label(value = "Overall Eligibility rule 3")
   private java.lang.String overalleligrule3;
   @org.kie.api.definition.type.Label(value = "Region Rule and result")
   private java.lang.String regionrule;

   public MemberDO()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public java.lang.Integer getMemberid()
   {
      return this.memberid;
   }

   public void setMemberid(java.lang.Integer memberid)
   {
      this.memberid = memberid;
   }

   public java.lang.Integer getTotalfamilyincome()
   {
      return this.totalfamilyincome;
   }

   public void setTotalfamilyincome(java.lang.Integer totalfamilyincome)
   {
      this.totalfamilyincome = totalfamilyincome;
   }

   public java.lang.Integer getPersonalincomefactor()
   {
      return this.personalincomefactor;
   }

   public void setPersonalincomefactor(java.lang.Integer personalincomefactor)
   {
      this.personalincomefactor = personalincomefactor;
   }

   public java.lang.Integer getFamilysize()
   {
      return this.familysize;
   }

   public void setFamilysize(java.lang.Integer familysize)
   {
      this.familysize = familysize;
   }

   public java.lang.Integer getAdditionalyfactor()
   {
      return this.additionalyfactor;
   }

   public void setAdditionalyfactor(java.lang.Integer additionalyfactor)
   {
      this.additionalyfactor = additionalyfactor;
   }

   public java.lang.String getRegion()
   {
      return this.region;
   }

   public void setRegion(java.lang.String region)
   {
      this.region = region;
   }

   public java.lang.Integer getFPL()
   {
      return this.FPL;
   }

   public void setFPL(java.lang.Integer FPL)
   {
      this.FPL = FPL;
   }

   public java.lang.Integer getSubage()
   {
      return this.subage;
   }

   public void setSubage(java.lang.Integer subage)
   {
      this.subage = subage;
   }

   public java.lang.Integer getSpouseage()
   {
      return this.spouseage;
   }

   public void setSpouseage(java.lang.Integer spouseage)
   {
      this.spouseage = spouseage;
   }

   public java.lang.Integer getDep1age()
   {
      return this.dep1age;
   }

   public void setDep1age(java.lang.Integer dep1age)
   {
      this.dep1age = dep1age;
   }

   public java.lang.Integer getDep2age()
   {
      return this.dep2age;
   }

   public void setDep2age(java.lang.Integer dep2age)
   {
      this.dep2age = dep2age;
   }

   public java.lang.String getOveralleligrule1()
   {
      return this.overalleligrule1;
   }

   public void setOveralleligrule1(java.lang.String overalleligrule1)
   {
      this.overalleligrule1 = overalleligrule1;
   }

   public java.lang.String getOveralleligrule2()
   {
      return this.overalleligrule2;
   }

   public void setOveralleligrule2(java.lang.String overalleligrule2)
   {
      this.overalleligrule2 = overalleligrule2;
   }

   public java.lang.String getOveralleligrule3()
   {
      return this.overalleligrule3;
   }

   public void setOveralleligrule3(java.lang.String overalleligrule3)
   {
      this.overalleligrule3 = overalleligrule3;
   }

   public java.lang.String getRegionrule()
   {
      return this.regionrule;
   }

   public void setRegionrule(java.lang.String regionrule)
   {
      this.regionrule = regionrule;
   }

   public MemberDO(java.lang.String name, java.lang.String zip,
         java.lang.Integer memberid, java.lang.Integer totalfamilyincome,
         java.lang.Integer personalincomefactor,
         java.lang.Integer familysize, java.lang.Integer additionalyfactor,
         java.lang.String region, java.lang.Integer FPL,
         java.lang.Integer subage, java.lang.Integer spouseage,
         java.lang.Integer dep1age, java.lang.Integer dep2age,
         java.lang.String overalleligrule1,
         java.lang.String overalleligrule2,
         java.lang.String overalleligrule3, java.lang.String regionrule)
   {
      this.name = name;
      this.zip = zip;
      this.memberid = memberid;
      this.totalfamilyincome = totalfamilyincome;
      this.personalincomefactor = personalincomefactor;
      this.familysize = familysize;
      this.additionalyfactor = additionalyfactor;
      this.region = region;
      this.FPL = FPL;
      this.subage = subage;
      this.spouseage = spouseage;
      this.dep1age = dep1age;
      this.dep2age = dep2age;
      this.overalleligrule1 = overalleligrule1;
      this.overalleligrule2 = overalleligrule2;
      this.overalleligrule3 = overalleligrule3;
      this.regionrule = regionrule;
   }

}